version: '3.8'

services:

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    ports:
      - 3305:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
